2020-11-09 17:00:11,296 - log - DEBUG -1399- NO
2020-11-09 17:00:11,313 - log - DEBUG -1402- DONE
2020-11-09 17:00:11,524 - log - INFO -1426- 程序启动成功!
2020-11-09 17:00:11,895 - log - INFO -1427- 版本：2.3-20200805
2020-11-09 17:00:36,916 - log - INFO -1390- 程序退出：
2020-11-09 17:12:36,274 - matchingTools.py - DEBUG -1397- Yes
2020-11-09 17:12:36,595 - matchingTools.py - INFO -1426- 程序启动成功!
2020-11-09 17:12:36,973 - matchingTools.py - INFO -1427- 版本：2.3-20200805
2020-11-09 17:13:34,258 - matchingTools.py - INFO -1390- 程序退出：
2020-11-09 17:13:37,421 - log.py - DEBUG -19- TEST for logging
2020-11-09 17:13:37,428 - matchingTools.py - DEBUG -1397- Yes
2020-11-09 17:13:37,624 - matchingTools.py - INFO -1426- 程序启动成功!
2020-11-09 17:13:37,924 - matchingTools.py - INFO -1427- 版本：2.3-20200805
2020-11-09 17:15:23,250 - matchingTools.py - INFO -1390- 程序退出：
2020-11-09 17:15:41,481 - log.py - DEBUG -18- TEST for logging
2020-11-09 17:15:41,483 - matchingTools.py - DEBUG -1397- Yes
2020-11-09 17:15:41,676 - matchingTools.py - INFO -1426- 程序启动成功!
2020-11-09 17:15:41,994 - matchingTools.py - INFO -1427- 版本：2.3-20200805
2020-11-09 17:16:02,555 - matchingTools.py - DEBUG -1048- self.is_bcPR.get():
2020-11-09 17:16:14,167 - matchingTools.py - DEBUG -457- 牧场名的拼音首字母
2020-11-09 17:16:14,168 - matchingTools.py - DEBUG -460- 执行的命令是：HY=Farm(洪雅,DSF.CSV,0)
2020-11-09 17:16:19,915 - matchingTools.py - DEBUG -457- 牧场名的拼音首字母
2020-11-09 17:16:19,915 - matchingTools.py - DEBUG -460- 执行的命令是：HY=Farm(洪雅,DSF.CSV,0)
2020-11-09 17:17:00,513 - matchingTools.py - INFO -1390- 程序退出：
2020-11-09 17:17:16,309 - log.py - DEBUG -18- TEST for logging
2020-11-09 17:17:16,313 - matching.py - INFO -14- ddddd test 
2020-11-09 17:17:16,315 - matchingTools.py - DEBUG -1397- Yes
2020-11-09 17:17:16,557 - matchingTools.py - INFO -1426- 程序启动成功!
2020-11-09 17:17:16,899 - matchingTools.py - INFO -1427- 版本：2.3-20200805
2020-11-09 17:17:31,066 - matchingTools.py - INFO -1390- 程序退出：
2020-11-09 17:30:17,212 - log.py - DEBUG -18- TEST for logging
2020-11-09 17:30:17,220 - matchingTools.py - DEBUG -1397- Yes
2020-11-09 17:30:17,560 - matchingTools.py - INFO -1426- 程序启动成功!
2020-11-09 17:30:17,963 - matchingTools.py - INFO -1427- 版本：2.3-20200805
2020-11-09 17:30:32,821 - matchingTools.py - DEBUG -457- 牧场名的拼音首字母
2020-11-09 17:30:32,822 - matchingTools.py - DEBUG -460- 执行的命令是：WS=Farm(汶上,tyesryh.csv,0)
2020-11-09 17:30:32,824 - matching.py - DEBUG -29- 牛群明细文件的后缀是：CSV
2020-11-09 17:32:29,980 - matchingTools.py - INFO -1390- 程序退出：
2020-11-09 17:32:32,055 - log.py - DEBUG -18- TEST for logging
2020-11-09 17:32:53,125 - log.py - DEBUG -18- TEST for logging
2020-11-09 17:32:53,147 - matchingTools.py - DEBUG -1398- Yes
2020-11-09 17:32:55,222 - matchingTools.py - INFO -1427- 程序启动成功!
2020-11-09 17:32:55,663 - matchingTools.py - INFO -1428- 版本：2.3-20200805
2020-11-09 17:33:02,932 - matchingTools.py - DEBUG -458- 牧场名的拼音首字母
2020-11-09 17:33:02,936 - matchingTools.py - DEBUG -461- 执行的命令是：WS=Farm(汶上,ddd.csv,0)
2020-11-09 17:33:02,937 - matching.py - DEBUG -29- 牛群明细文件的后缀是：CSV
2020-11-09 17:33:02,939 - matchingTools.py - DEBUG -49- 错误: Traceback (most recent call last):
  File "c:/Users/runda/OneDrive - RundaTech/PortableApps/PortableApps/VSCode/data/ToolsALTA/matchingTools.py", line 462, in load_btnEvent
    exec('self.farm_code=Farm(self.farm.get(),self.herds.get(),' +
  File "<string>", line 1, in <module>
  File "c:\Users\runda\OneDrive - RundaTech\PortableApps\PortableApps\VSCode\data\ToolsALTA\matching.py", line 31, in __init__
    demand = pickle.load(db)['demand']
NameError: name 'pickle' is not defined

2020-11-09 17:34:53,026 - matchingTools.py - DEBUG -458- 牧场名的拼音首字母
2020-11-09 17:34:53,027 - matchingTools.py - DEBUG -461- 执行的命令是：WS=Farm(汶上,ddd.csv,0)
2020-11-09 17:34:53,027 - matching.py - DEBUG -29- 牛群明细文件的后缀是：CSV
2020-11-09 17:34:53,029 - matchingTools.py - DEBUG -49- 错误: Traceback (most recent call last):
  File "c:/Users/runda/OneDrive - RundaTech/PortableApps/PortableApps/VSCode/data/ToolsALTA/matchingTools.py", line 462, in load_btnEvent
    exec('self.farm_code=Farm(self.farm.get(),self.herds.get(),' +
  File "<string>", line 1, in <module>
  File "c:\Users\runda\OneDrive - RundaTech\PortableApps\PortableApps\VSCode\data\ToolsALTA\matching.py", line 31, in __init__
    with open(DB, 'rb') as db:
NameError: name 'pickle' is not defined

2020-11-09 17:34:56,571 - matchingTools.py - INFO -1391- 程序退出：
2020-11-09 17:35:00,441 - log.py - DEBUG -18- TEST for logging
2020-11-09 17:35:00,443 - matchingTools.py - DEBUG -1398- Yes
2020-11-09 17:35:00,675 - matchingTools.py - INFO -1427- 程序启动成功!
2020-11-09 17:35:00,990 - matchingTools.py - INFO -1428- 版本：2.3-20200805
2020-11-09 17:35:06,498 - matchingTools.py - DEBUG -458- 牧场名的拼音首字母
2020-11-09 17:35:06,498 - matchingTools.py - DEBUG -461- 执行的命令是：HL=Farm(和林,ddf.csv,0)
2020-11-09 17:35:06,499 - matching.py - DEBUG -30- 牛群明细文件的后缀是：CSV
2020-11-09 17:35:06,503 - matching.py - DEBUG -44- 牧场的参数为：
  ['和林', '102', '0', '1', '2', '0', '0', '0', '6', 'nothing']
2020-11-09 17:35:06,505 - matchingTools.py - DEBUG -49- 错误: Traceback (most recent call last):
  File "c:/Users/runda/OneDrive - RundaTech/PortableApps/PortableApps/VSCode/data/ToolsALTA/matchingTools.py", line 462, in load_btnEvent
    exec('self.farm_code=Farm(self.farm.get(),self.herds.get(),' +
  File "<string>", line 1, in <module>
  File "c:\Users\runda\OneDrive - RundaTech\PortableApps\PortableApps\VSCode\data\ToolsALTA\matching.py", line 45, in __init__
    self.herds = self.import_cowsFile()   # 导入牛群明细
  File "c:\Users\runda\OneDrive - RundaTech\PortableApps\PortableApps\VSCode\data\ToolsALTA\matching.py", line 55, in import_cowsFile
    herds = pd.DataFrame()
NameError: name 'pd' is not defined

2020-11-09 17:35:51,475 - matchingTools.py - INFO -1391- 程序退出：
2020-11-09 17:35:53,196 - log.py - DEBUG -18- TEST for logging
2020-11-09 17:35:58,883 - matchingTools.py - DEBUG -1398- Yes
2020-11-09 17:35:59,257 - matchingTools.py - INFO -1427- 程序启动成功!
2020-11-09 17:35:59,946 - matchingTools.py - INFO -1428- 版本：2.3-20200805
2020-11-09 17:37:30,223 - matchingTools.py - DEBUG -458- 牧场名的拼音首字母
2020-11-09 17:37:30,226 - matchingTools.py - DEBUG -461- 执行的命令是：HY=Farm(洪雅,ddd.csv,0)
2020-11-09 17:37:30,227 - matching.py - DEBUG -51- 牛群明细文件的后缀是：CSV
2020-11-09 17:37:30,227 - matching.py - DEBUG -65- 牧场的参数为：
  ['洪雅', '103', '0', '1', '2', '0', '0', '0', '30', 'nothing']
2020-11-09 17:37:30,233 - matching.py - INFO -91- 

开始执行第一步：导入牛群明细...
2020-11-09 17:37:30,266 - matching.py - INFO -92- 参数为：
  牛群明细：ddd.csv
...
2020-11-09 17:37:30,281 - matching.py - DEBUG -94- overload: 0
2020-11-09 17:37:30,281 - matching.py - DEBUG -95- <class 'int'>
2020-11-09 17:37:30,282 - matching.py - DEBUG -115- 文件后缀是: CSV
2020-11-09 17:37:30,287 - matchingTools.py - DEBUG -49- 错误: Traceback (most recent call last):
  File "c:/Users/runda/OneDrive - RundaTech/PortableApps/PortableApps/VSCode/data/ToolsALTA/matchingTools.py", line 462, in load_btnEvent
    exec('self.farm_code=Farm(self.farm.get(),self.herds.get(),' +
  File "<string>", line 1, in <module>
  File "c:\Users\runda\OneDrive - RundaTech\PortableApps\PortableApps\VSCode\data\ToolsALTA\matching.py", line 66, in __init__
    self.herds = self.import_cowsFile()   # 导入牛群明细
  File "c:\Users\runda\OneDrive - RundaTech\PortableApps\PortableApps\VSCode\data\ToolsALTA\matching.py", line 118, in import_cowsFile
    herds_file, encoding='gbk'))
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1874, in __init__
    src = open(src, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\runda\\OneDrive - RundaTech\\PortableApps\\PortableApps\\VSCode\\data\\ToolsALTA\\Match_files\\ddd.csv'

2020-11-09 17:41:10,129 - matchingTools.py - INFO -1391- 程序退出：
2020-11-09 17:41:11,892 -log.py -<module> -DEBUG-19-TEST for logging
2020-11-09 17:41:13,055 -matchingTools.py -<module> -DEBUG-1398-Yes
2020-11-09 17:41:13,378 -matchingTools.py -<module> -INFO-1427-程序启动成功!
2020-11-09 17:41:13,762 -matchingTools.py -<module> -INFO-1428-版本：2.3-20200805
2020-11-09 17:41:40,676 -matchingTools.py -load_btnEvent -DEBUG-458-牧场名的拼音首字母
2020-11-09 17:41:40,676 -matchingTools.py -load_btnEvent -DEBUG-461-执行的命令是：HY=Farm(洪雅,fff.csv,0)
2020-11-09 17:41:40,676 -matching.py -__init__ -DEBUG-51-牛群明细文件的后缀是：CSV
2020-11-09 17:41:40,676 -matching.py -__init__ -DEBUG-65-牧场的参数为：
  ['洪雅', '103', '0', '1', '2', '0', '0', '0', '30', 'nothing']
2020-11-09 17:41:40,686 -matching.py -import_cowsFile -INFO-91-

开始执行第一步：导入牛群明细...
2020-11-09 17:41:40,686 -matching.py -import_cowsFile -INFO-92-参数为：
  牛群明细：fff.csv
...
2020-11-09 17:41:40,697 -matching.py -import_cowsFile -DEBUG-94-overload: 0
2020-11-09 17:41:40,697 -matching.py -import_cowsFile -DEBUG-95-<class 'int'>
2020-11-09 17:41:40,697 -matching.py -import_cowsFile -DEBUG-115-文件后缀是: CSV
2020-11-09 17:41:40,706 -matchingTools.py -out_error -DEBUG-49-错误: Traceback (most recent call last):
  File "c:/Users/runda/OneDrive - RundaTech/PortableApps/PortableApps/VSCode/data/ToolsALTA/matchingTools.py", line 462, in load_btnEvent
    exec('self.farm_code=Farm(self.farm.get(),self.herds.get(),' +
  File "<string>", line 1, in <module>
  File "c:\Users\runda\OneDrive - RundaTech\PortableApps\PortableApps\VSCode\data\ToolsALTA\matching.py", line 66, in __init__
    self.herds = self.import_cowsFile()   # 导入牛群明细
  File "c:\Users\runda\OneDrive - RundaTech\PortableApps\PortableApps\VSCode\data\ToolsALTA\matching.py", line 118, in import_cowsFile
    herds_file, encoding='gbk'))
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1874, in __init__
    src = open(src, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\runda\\OneDrive - RundaTech\\PortableApps\\PortableApps\\VSCode\\data\\ToolsALTA\\Match_files\\fff.csv'

2020-11-09 17:43:33,098 -matchingTools.py -quite -INFO-1391-程序退出：
